# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83a05bb41234c0129c6ede1994ddf9a814fa6094727278f1175f50d921b451f2b9bc9b6ac78ffd4e61da707c255478950a842593ee07732c749814fb8758b3df
  google_client_id: test
  google_client_secret: test

test:
  secret_key_base: 4a1fa7966afe69634171464e29361c5343ef98f6afebd028265affa138d46ca375f4e7194e07ec0bc658d934c16647c70b2f5dd79422869290dd2c6669e04c24

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
